[package]
name = "cotp"
version = "1.3.0"
authors = ["replydev <commoncargo@tutanota.com>"]
edition = "2021"
description = "Trustworthy, encrypted, command-line TOTP/HOTP authenticator app with import functionality."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities", "authentication"]
keywords = ["cotp", "totp", "authenticator", "google-authenticator", "argon2"]

# Set bin name for CI 
[[bin]]
name = "cotp"
path = "src/main.rs"

# Optimize release binary size
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
debug = false
strip = "symbols"

[dependencies]
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }
dirs = "5.0.1"
rpassword = "7.2.0"
data-encoding = "2.4.0"
copypasta-ext = "0.4.4"
zeroize = "1.6.0"
clap = { version = "4.3.19", features = ["derive"] }
hmac = "0.12.1"
sha-1 = "0.10.1"
sha2 = "0.10.7"
chacha20poly1305 = "0.10.1"
rust-argon2 = "1.0"
getrandom = "0.2.10"
scrypt = "0.11.0"
aes-gcm = "0.10.2"
hex = "0.4.3"
qrcode = "0.12.0"
urlencoding = "2.1.3"
regex = "1.9.1"
once_cell = "1.18.0"
base64 = "0.21.2"
md-5 = "0.10.5"
ratatui = { version = "0.22.0", features = ["all-widgets"] }
crossterm = "0.26.1"
