[package]
name = "cotp"
version = "0.2.1"
authors = ["replydev <commoncargo@tutanota.com>"]
edition = "2021"
description = "Trustworthy, encrypted, command-line TOTP/HOTP authenticator app with import functionality."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google-authenticator","argon2"]

# Set bin name for CI 
[[bin]]
name = "cotp"
path = "src/main.rs"

# Optimize release binary size
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
dirs = "4.0.0"
rpassword = "6.0.1"
data-encoding = "2.3.2"
crossterm = "0.23.2"
tui = "0.18.0"
copypasta-ext = "0.3.9"
zeroize = "1.4.3"
clap = "3.2.5"
hmac = "0.12.1"
sha-1 = "0.10.0"
sha2 = "0.10.2"
chacha20poly1305 = "0.9.0"
rust-argon2 = "1.0"
getrandom = "0.2.7"
scrypt = "0.10.0"
aes-gcm = "0.9.4"
hex = "0.4.3"
qrcode = "0.12.0"
urlencoding = "2.1.0"
base64 = "0.13.0"