[package]
name = "cotp"
version = "1.2.4"
authors = ["replydev <commoncargo@tutanota.com>"]
edition = "2021"
description = "Trustworthy, encrypted, command-line TOTP/HOTP authenticator app with import functionality."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google-authenticator","argon2"]

# Set bin name for CI 
[[bin]]
name = "cotp"
path = "src/main.rs"

# Optimize release binary size
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
debug  = false
strip = "symbols"

[dependencies]
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
dirs = "5.0.1"
rpassword = "7.2.0"
data-encoding = "2.4.0"
crossterm = "0.26.1"
tui = "0.19.0"
copypasta-ext = "0.4.4"
zeroize = "1.6.0"     
clap = "4.2.7"
hmac = "0.12.1"
sha-1 = "0.10.1"
sha2 = "0.10.6"
chacha20poly1305 = "0.10.1"
rust-argon2 = "1.0"
getrandom = "0.2.9"
scrypt = "0.11.0"
aes-gcm = "0.10.1"
hex = "0.4.3"
qrcode = "0.12.0"
urlencoding = "2.1.2"
regex = "1.8.1"
lazy_static = "1.4.0"
base64 = "0.21.0"
md-5 = "0.10.5"
