[package]
name = "cotp"
version = "0.1.8"
authors = ["replydev <commoncargo@tutanota.com>"]
edition = "2018"
description = "Trustworthy, encrypted, command-line TOTP/HOTP authenticator app with import functionality."
repository = "https://github.com/replydev/cotp"
homepage = "https://github.com/replydev/cotp"
documentation = "https://github.com/replydev/cotp/blob/master/README.md"
readme = "README.md"
license-file = "LICENSE"
categories = ["command-line-utilities","authentication"]
keywords = ["cotp","totp","authenticator","google-authenticator","argon2"]

[dependencies]
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
dirs = "4.0.0"
rpassword = "5.0.1"
sodiumoxide = "0.2.7"
data-encoding = "2.3.2"
crossterm = "0.21.0"
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }
copypasta-ext = "0.3.7"
zeroize = "1.4.2"
clap = "3.0.0-beta.5"
hmac = "0.11.0"
sha-1 = "0.9.8"
sha2 = "0.9.8"